
[esConfig]
clsPushHost="http://c2-media-mix02.bj:9200/newserverlog_cls_publisher_online/_search?pretty"
cdnPullOpenHost="http://c2-media-mix02.bj:9200/new_cdn_pull_open_detail_online/_search?pretty"

[server]
	service_name="media.monitor.realTimeIndex"
	port = 10000

[log]
	level="debug"
	logpath="logs"
	rotate="hour"

