
[esHost]
pushHost="http://c2-media-mix02.bj:9200/media_new_sdk_push/_search?pretty"
pullHost="http://c2-media-mix02.bj:9200/media_new_sdk_pull/_search?pretty"
openHost="http://c2-media-mix02.bj:9200/media_new_sdk_open/_search?pretty"

[server]
	service_name="media.monitor.realTimeIndex"
	port = 10000

[sqlTblName]
esDealResTblName="media_realTime_EsDealResTblName"

[log]
	level="debug"
	logpath="logs"
	rotate="hour"

