//Generated by the daenerys tool.  DO NOT EDIT!
package model

type Model struct {
}

type QueryInfo struct {
	HostName    string            // 查询host地址信息，如：http://c2-media-mix02.bj:9200/new_cdn_pull_open_detail_online/_search?pretty
	Group       []string          //分组条件
	Filter      map[string]string //过滤条件
	Target      string            //查询目标对象
	Method      string            //执行方法，支持：avg-平均值，max-最大值，min-最小值，sum-和，count-总数
	Minute      int               //minute分钟内的数据，比如现在30分钟，求的是26-27分钟的数据，延时3分钟防止无数据
	StartTime   string            // 开始时间
	EndTime     string            // 结束时间
	GroupFilter int               //表示分组条件和过滤添加的个数，如20，表示2个分组条件和0个过滤条件
}

type Oper_target struct {
	Value float64 `json:"value"`
}

type CoreBuckets struct {
	CoreKey        string      `json:"key"`
	CoreCount      float64     `json:"doc_count"`
	CoreOperTarget Oper_target `json:"oper_target"`
}

type Group_by_group2 struct {
	CoreBuckets []CoreBuckets `json:"buckets"`
}

type Buckets struct {
	Key         string          `json:"key"`
	Doc_count   float64         `json:"doc_count"`
	Oper_target Oper_target     `json:"oper_target"` // 试试
	Group2      Group_by_group2 `json:"group_by_group2"`
}

type Group_by_group1 struct {
	Buckets []Buckets `json:"buckets"`
}

type Aggregations struct {
	Group1 Group_by_group1 `json:"group_by_group1"`
}

type Hits struct {
	Total float64 `json:"total"`
}

type QueryRes struct {
	Hits         Hits         `json:"hits"`
	Aggregations Aggregations `json:"aggregations"`
}

type GroupFilter10Res struct {
	Hits         Hits         `json:"hits"`
	Aggregations Aggregations `json:"aggregations"`
}

type GF20MysqlInfo struct {
	Ymd        string  `gorm:"ymd"`
	AppName    string  `gorm:"appname"`
	Cv         string  `gorm:"cv"`
	All_Total  float64 `gorm:"all_total"`  //总数
	Sec_Total  float64 `gorm:"sec_total"`  //第二层total
	Res_Total  float64 `gorm:"res_total"`  //结果total
	Value      float64 `gorm:"value"`      //结果值
	Event_Time int64   `gorm:"event_time"` //时间戳
}
